backend:
  name: github
  repo: cguttweb/nuxt-portfolio-blog

media_folder: 'static/uploads'
public_folder: '/uploads'
publish_mode: editorial_workflow

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }


